[project]
name = 'Decentralized-Environmental-Carbon-Sequestration-Tracking'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.credit-issuance]
path = 'contracts/credit-issuance.clar'
clarity_version = 2
epoch = 2.5

[contracts.monitoring-protocol]
path = 'contracts/monitoring-protocol.clar'
clarity_version = 2
epoch = 2.5

[contracts.project-verification]
path = 'contracts/project-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
